import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { Provider } from 'react-redux'
import { ReactNode } from 'react'
import Head from "next/head"
import Layout from "@components/Layout/Layout"
import NextNProgress from 'nextjs-progressbar';
import { store } from 'redux/store/store'
export default function App({ Component, pageProps }: AppProps): ReactNode {
  return (
    <>
      <NextNProgress
        color="#124"
        startPosition={0.3}
        height={3}
        options={{ easing: 'ease-in-out', speed: 400 }}
      />
      <Head>
        <title>Online Shoe Store | Tu Dev</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />

        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="use-credentials"
        />
      </Head>
      <link
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet"
      />
      <Provider store={store}>
        <Layout>
          <main>
            <Component {...pageProps} />
          </main>
        </Layout>
      </Provider>
    </>
  )
}
